-- =====================================================
-- BASE DE DATOS: FACCARPRUEBA
-- Esquema con patrón SIST_ para tablas y campos
-- Versión completa con campos duplicados y firmas
-- =====================================================

PRINT '🚀 Iniciando creación/actualización de base de datos FACCARPRUEBA...'
PRINT '📋 Incluye campos duplicados (2 fechas nacimiento 2 teléfonos) y campos de firmas'

-- =====================================================
-- TABLA PRINCIPAL: SIST_ORDEN_COMPRA
-- Contiene todos los campos de la orden de compra
-- =====================================================

CREATE TABLE SIST_ORDEN_COMPRA (
    OC_ID INT IDENTITY(1,1) PRIMARY KEY,
    OC_FECHA_CREACION DATETIME DEFAULT GETDATE(),

    -- ENCABEZADO (orden del formulario)
    OC_NUMERO_EXPEDIENTE NVARCHAR(50),
    OC_NUMERO_COTIZACION NVARCHAR(50),
    
    -- CENTRO DE COSTO Y APROBACIÓN (orden del formulario)
    OC_AGENCIA NVARCHAR(100),
    OC_NOMBRE_RESPONSABLE NVARCHAR(200),
    OC_CENTRO_COSTO NVARCHAR(50),
    OC_EMAIL_CENTRO_COSTO NVARCHAR(150),
    
    OC_FECHA_ORDEN DATE,
    OC_ASESOR_VENTA NVARCHAR(100),

    -- DATOS DEL CLIENTE - COMPRADOR (orden del formulario)
    OC_COMPRADOR_NOMBRE NVARCHAR(200),
    OC_COMPRADOR_TIPO_DOCUMENTO NVARCHAR(20), -- DNI, PASAPORTE, CARNET EXTRANJERIA, RUC
    OC_COMPRADOR_NUMERO_DOCUMENTO NVARCHAR(20),
    OC_TIPO_DOCUMENTO_VENTA NVARCHAR(20), -- BOLETA DE VENTA, FACTURA DE VENTA
    OC_FUENTE_CONTACTO NVARCHAR(100), -- Digital Marca, Digital Dealer, etc.
    OC_TIPO_CLIENTE NVARCHAR(50), -- Tipo de cliente: natural, ruc, juridica

    -- INFORMACIÓN PERSONAL DEL CLIENTE (orden del formulario)
    OC_FECHA_NACIMIENTO DATE, -- Primera fecha de nacimiento (junto a estado civil)
    OC_ESTADO_CIVIL NVARCHAR(20), -- SOLTERO, CASADO, DIVORCIADO, SEPARADO, CONCUBINA(O), CONVIVIENTE
    OC_SITUACION_LABORAL NVARCHAR(50), -- EMPLEADO, INDEPENDIENTE, NEGOCIANTE, JUBILADO, DEPENDIENTE, DESEMPLEADO, OTROS

    -- DATOS DEL CÓNYUGE (orden del formulario)
    OC_CONYUGE_NOMBRE NVARCHAR(200),
    OC_CONYUGE_TIPO_DOCUMENTO NVARCHAR(20),
    OC_CONYUGE_NUMERO_DOCUMENTO NVARCHAR(20),

    -- INFORMACIÓN DE CONTACTO (orden del formulario)
    OC_DIRECCION_CLIENTE NVARCHAR(300),
    OC_TELEFONO_CLIENTE NVARCHAR(100), -- Teléfono principal
    OC_EMAIL_CLIENTE NVARCHAR(150),
    OC_TELEFONO_ADICIONAL NVARCHAR(100), -- Teléfono adicional
    OC_OCUPACION_CLIENTE NVARCHAR(100),
    OC_HOBBIES_CLIENTE NVARCHAR(200),
    OC_FECHA_NACIMIENTO_NUEVO DATE, -- Segunda fecha de nacimiento (junto a hobbies)

    -- TARJETA DE PROPIEDAD (orden del formulario)
    OC_TARJETA_PROPIEDAD NVARCHAR(50), -- natural, ruc, juridica

    -- PROPIETARIOS (orden del formulario)
    OC_PROPIETARIO_NOMBRE NVARCHAR(200),
    OC_PROPIETARIO_DNI NVARCHAR(20),
    OC_COPROPIETARIO_NOMBRE NVARCHAR(200),
    OC_COPROPIETARIO_DNI NVARCHAR(20),
    OC_REPRESENTANTE_LEGAL NVARCHAR(200),
    OC_REPRESENTANTE_DNI NVARCHAR(20),

    -- DATOS DEL VEHÍCULO (orden del formulario)
    OC_VEHICULO_CLASE NVARCHAR(100),
    OC_VEHICULO_MARCA NVARCHAR(100),
    OC_VEHICULO_MODELO NVARCHAR(100),
    OC_VEHICULO_VERSION NVARCHAR(100),
    OC_VEHICULO_CODIGO_FSC NVARCHAR(100),
    OC_VEHICULO_MOTOR NVARCHAR(100),
    OC_VEHICULO_CHASIS NVARCHAR(100),
    OC_VEHICULO_COLOR NVARCHAR(50),
    OC_VEHICULO_ANIO_MODELO NVARCHAR(10),
    OC_PERIODO_GARANTIA NVARCHAR(100),
    OC_PERIODICIDAD_MANTENIMIENTO NVARCHAR(100),
    OC_PRIMER_MANTENIMIENTO NVARCHAR(100),

    -- VALOR DE LA COMPRA / FORMA DE PAGO (orden del formulario)
    OC_FORMA_PAGO NVARCHAR(20), -- CONTADO, CRÉDITO
    OC_PRECIO_VENTA DECIMAL(12,2),
    OC_MONEDA_PRECIO_VENTA NVARCHAR(5), -- US$, MN
    OC_BONO_FINANCIAMIENTO DECIMAL(12,2),
    OC_MONEDA_BONO_FINANCIAMIENTO NVARCHAR(5),

    -- EQUIPAMIENTO ADICIONAL (orden del formulario)
    OC_DESCRIPCION_EQUIPAMIENTO_1 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_1 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_1 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_2 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_2 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_2 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_3 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_3 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_3 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_4 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_4 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_4 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_5 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_5 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_5 NVARCHAR(5),

    OC_TOTAL_EQUIPAMIENTO DECIMAL(12,2),
    OC_PRECIO_TOTAL_COMPRA DECIMAL(12,2),
    OC_MONEDA_PRECIO_TOTAL NVARCHAR(5),
    OC_TIPO_CAMBIO DECIMAL(8,4),
    OC_TIPO_CAMBIO_SOL DECIMAL(12,2),

    -- FORMA DE PAGO - COLUMNA DERECHA (orden del formulario)
    OC_PAGO_CUENTA DECIMAL(12,2),
    OC_MONEDA_PAGO_CUENTA NVARCHAR(5),
    OC_NUMERO_OPERACION NVARCHAR(50),
    OC_NUMERO_OPERACION_2 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA NVARCHAR(100),
    OC_SALDO_PENDIENTE DECIMAL(12,2),
    OC_MONEDA_SALDO NVARCHAR(5),

    -- INFORMACIÓN BANCARIA (orden del formulario)
    OC_BANCO_ABONO NVARCHAR(100),
    OC_SECTORISTA_BANCO NVARCHAR(100),
    OC_OFICINA_BANCO NVARCHAR(100),
    OC_TELEFONO_SECTORISTA NVARCHAR(20),

    -- OBSEQUIOS Y CAMPAÑAS (orden del formulario)
    OC_OBSEQUIOS_CORTESIAS NVARCHAR(MAX),

    -- FIRMAS Y HUELLAS (orden del formulario)
    OC_ASESOR_NOMBRE NVARCHAR(200), -- Nombre del asesor de venta
    OC_ASESOR_FIRMA NVARCHAR(200), -- Firma del asesor
    OC_ASESOR_HUELLA NVARCHAR(200), -- Huella del asesor
    OC_CLIENTE_FIRMA NVARCHAR(200), -- Firma del cliente
    OC_CLIENTE_HUELLA NVARCHAR(200), -- Huella del cliente
    OC_JEFE_NOMBRE NVARCHAR(200), -- Nombre del jefe de tienda
    OC_JEFE_FIRMA NVARCHAR(200), -- Firma del jefe
    OC_JEFE_HUELLA NVARCHAR(200), -- Huella del jefe
    OC_VISTO_ADV NVARCHAR(200), -- Visto ADV (por definir)

    -- ARCHIVOS ADJUNTOS (orden del formulario)
    OC_ARCHIVO_DNI NVARCHAR(500),
    OC_ARCHIVO_VOUCHER NVARCHAR(500),
    OC_ARCHIVO_PEDIDO_SALESFORCE NVARCHAR(500),
    OC_ARCHIVO_DERIVACION_SANTANDER NVARCHAR(500),
    OC_ARCHIVO_ABONO_1 NVARCHAR(500),
    OC_ARCHIVO_ABONO_2 NVARCHAR(500),
    OC_ARCHIVO_ABONO_3 NVARCHAR(500),
    OC_ARCHIVO_ABONO_4 NVARCHAR(500),
    OC_ARCHIVO_ABONO_5 NVARCHAR(500),
    OC_ARCHIVO_ABONO_6 NVARCHAR(500),
    OC_ARCHIVO_OTROS_1 NVARCHAR(500),
    OC_ARCHIVO_OTROS_2 NVARCHAR(500),
    OC_ARCHIVO_OTROS_3 NVARCHAR(500),
    OC_ARCHIVO_OTROS_4 NVARCHAR(500),
    OC_ARCHIVO_OTROS_5 NVARCHAR(500),
    OC_ARCHIVO_OTROS_6 NVARCHAR(500),

    -- CAMPOS DE APROBACIÓN
    OC_ESTADO_APROBACION NVARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, APROBADO, RECHAZADO
    OC_FECHA_APROBACION DATETIME,
    OC_OBSERVACIONES_APROBACION NVARCHAR(500)
);
;

-- =====================================================
-- TABLA: SIST_ACTA_CONOCIMIENTO_CONFORMIDAD
-- =====================================================

CREATE TABLE SIST_ACTA_CONOCIMIENTO_CONFORMIDAD (
    ACC_ID INT IDENTITY(1,1) PRIMARY KEY,
    ACC_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ACC_DOCUMENTO_VENTA_ID INT,

    -- Datos del acta
    ACC_FECHA_ACTA DATE,
    ACC_NOMBRE_CLIENTE NVARCHAR(200),
    ACC_DNI_CLIENTE NVARCHAR(20),
    ACC_EMPRESA_INSTALADORA NVARCHAR(200),

    -- Datos del vehículo
    ACC_BOLETA_FACTURA_NUMERO NVARCHAR(50),
    ACC_CLIENTE_VEHICULO NVARCHAR(200),
    ACC_FECHA_VENTA DATE,
    ACC_MARCA_VEHICULO NVARCHAR(100),
    ACC_MODELO_VEHICULO NVARCHAR(100),
    ACC_ANIO_VEHICULO NVARCHAR(10),
    ACC_VIN_VEHICULO NVARCHAR(50),
    ACC_COLOR_VEHICULO NVARCHAR(50),

    -- Firmas
    ACC_FIRMA_CLIENTE NVARCHAR(200),
    ACC_NOMBRE_FIRMA NVARCHAR(200),
    ACC_DNI_FIRMA NVARCHAR(20),

    FOREIGN KEY (ACC_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_AUTORIZACION_DATOS_PERSONALES
-- =====================================================

CREATE TABLE SIST_AUTORIZACION_DATOS_PERSONALES (
    ADP_ID INT IDENTITY(1,1) PRIMARY KEY,
    ADP_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ADP_DOCUMENTO_VENTA_ID INT,

    -- Datos de autorización
    ADP_NOMBRE_AUTORIZACION NVARCHAR(200),
    ADP_DNI_AUTORIZACION NVARCHAR(20),
    ADP_FECHA_AUTORIZACION DATE,

    FOREIGN KEY (ADP_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_CARTA_CONOCIMIENTO_ACEPTACION
-- =====================================================

CREATE TABLE SIST_CARTA_CONOCIMIENTO_ACEPTACION (
    CCA_ID INT IDENTITY(1,1) PRIMARY KEY,
    CCA_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CCA_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    CCA_CLIENTE_NOMBRE_COMPLETO NVARCHAR(200),
    CCA_CLIENTE_DOCUMENTO NVARCHAR(50),

    -- Datos del vehículo
    CCA_VEHICULO_MARCA NVARCHAR(100),
    CCA_VEHICULO_MODELO NVARCHAR(100),
    CCA_VEHICULO_ANIO NVARCHAR(10),
    CCA_VEHICULO_VIN NVARCHAR(50),

    -- Firmas
    CCA_FIRMA_CLIENTE NVARCHAR(200),
    CCA_NOMBRE_FIRMA NVARCHAR(200),
    CCA_DOCUMENTO_FIRMA NVARCHAR(50),
    CCA_FECHA_FIRMA DATE,

    FOREIGN KEY (CCA_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_CARTA_RECEPCION
-- =====================================================

CREATE TABLE SIST_CARTA_RECEPCION (
    CR_ID INT IDENTITY(1,1) PRIMARY KEY,
    CR_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CR_DOCUMENTO_VENTA_ID INT,

    -- Fechas
    CR_FECHA_DIA NVARCHAR(2),
    CR_FECHA_MES NVARCHAR(20),
    CR_FECHA_ANIO NVARCHAR(4),

    -- Datos del cliente
    CR_CLIENTE_NOMBRE NVARCHAR(200),
    CR_CLIENTE_DNI NVARCHAR(20),

    -- Datos del vehículo
    CR_VEHICULO_MARCA NVARCHAR(100),
    CR_VEHICULO_MODELO NVARCHAR(100),

    FOREIGN KEY (CR_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_CARTA_CARACTERISTICAS
-- =====================================================

CREATE TABLE SIST_CARTA_CARACTERISTICAS (
    CC_ID INT IDENTITY(1,1) PRIMARY KEY,
    CC_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CC_DOCUMENTO_VENTA_ID INT,

    -- Encabezado
    CC_FECHA_CARTA NVARCHAR(100),
    CC_EMPRESA_DESTINO NVARCHAR(200),

    -- Datos del cliente
    CC_CLIENTE_NOMBRE NVARCHAR(200),
    CC_CLIENTE_DNI NVARCHAR(20),

    -- Datos del vehículo
    CC_VEHICULO_MARCA NVARCHAR(100),
    CC_VEHICULO_MODELO NVARCHAR(100),
    CC_VEHICULO_ANIO_MODELO NVARCHAR(10),
    CC_VEHICULO_CHASIS NVARCHAR(50),
    CC_VEHICULO_MOTOR NVARCHAR(50),
    CC_VEHICULO_CARROCERIA NVARCHAR(50),
    CC_VEHICULO_COLOR NVARCHAR(50),

    -- Valores
    CC_PRECIO_VEHICULO DECIMAL(12,2),
    CC_CUOTA_INICIAL DECIMAL(12,2),
    CC_MONTO_APROBADO_NETO DECIMAL(12,2),
    CC_CAMPANA_VEHICULO NVARCHAR(200),
    CC_PROPIETARIO_TARJETA NVARCHAR(200),

    FOREIGN KEY (CC_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- VERIFICACIÓN Y ACTUALIZACIÓN AUTOMÁTICA
-- Agrega campos faltantes si la tabla ya existe
-- =====================================================

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'SIST_CARTA_CARACTERISTICAS')
BEGIN
    PRINT '📋 Verificando tabla SIST_CARTA_CARACTERISTICAS...';

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_CARTA_CARACTERISTICAS') AND name = 'CC_CUOTA_INICIAL')
    BEGIN
        ALTER TABLE SIST_CARTA_CARACTERISTICAS ADD CC_CUOTA_INICIAL DECIMAL(12,2);
        PRINT '✅ Campo CC_CUOTA_INICIAL agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_CARTA_CARACTERISTICAS') AND name = 'CC_MONTO_APROBADO_NETO')
    BEGIN
        ALTER TABLE SIST_CARTA_CARACTERISTICAS ADD CC_MONTO_APROBADO_NETO DECIMAL(12,2);
        PRINT '✅ Campo CC_MONTO_APROBADO_NETO agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_CARTA_CARACTERISTICAS') AND name = 'CC_CAMPANA_VEHICULO')
    BEGIN
        ALTER TABLE SIST_CARTA_CARACTERISTICAS ADD CC_CAMPANA_VEHICULO NVARCHAR(200);
        PRINT '✅ Campo CC_CAMPANA_VEHICULO agregado.';
    END

    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_CARTA_CARACTERISTICAS') AND name = 'CC_MONTO_DESEMBOLSO')
    BEGIN
        ALTER TABLE SIST_CARTA_CARACTERISTICAS DROP COLUMN CC_MONTO_DESEMBOLSO;
        PRINT '✅ Campo CC_MONTO_DESEMBOLSO eliminado.';
    END
END
;

-- =====================================================
-- TABLA: SIST_CARTA_FELICITACIONES
-- =====================================================

CREATE TABLE SIST_CARTA_FELICITACIONES (
    CF_ID INT IDENTITY(1,1) PRIMARY KEY,
    CF_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CF_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    CF_CLIENTE_NOMBRE NVARCHAR(200),
    CF_VEHICULO_MARCA NVARCHAR(100),

    -- Datos del asesor
    CF_ASESOR_NOMBRE NVARCHAR(200),
    CF_ASESOR_CELULAR NVARCHAR(20),

    -- Aplicación
    CF_APLICACION_NOMBRE NVARCHAR(200),

    FOREIGN KEY (CF_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- ÍNDICES PARA MEJOR PERFORMANCE
-- =====================================================

CREATE INDEX IDX_OC_FECHA_ORDEN ON SIST_ORDEN_COMPRA(OC_FECHA_ORDEN);
CREATE INDEX IDX_OC_CLIENTE_NOMBRE ON SIST_ORDEN_COMPRA(OC_COMPRADOR_NOMBRE);
CREATE INDEX IDX_OC_ASESOR_VENTA ON SIST_ORDEN_COMPRA(OC_ASESOR_VENTA);

CREATE INDEX IDX_ACC_FECHA_ACTA ON SIST_ACTA_CONOCIMIENTO_CONFORMIDAD(ACC_FECHA_ACTA);
CREATE INDEX IDX_ADP_FECHA_AUTORIZACION ON SIST_AUTORIZACION_DATOS_PERSONALES(ADP_FECHA_AUTORIZACION);
CREATE INDEX IDX_CCA_FECHA_FIRMA ON SIST_CARTA_CONOCIMIENTO_ACEPTACION(CCA_FECHA_FIRMA);

-- =====================================================
-- TABLA: SIST_CARTA_OBSEQUIOS
-- =====================================================

CREATE TABLE SIST_CARTA_OBSEQUIOS (
    CO_ID INT IDENTITY(1,1) PRIMARY KEY,
    CO_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CO_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    CO_CLIENTE_NOMBRE NVARCHAR(200),
    CO_CLIENTE_DNI NVARCHAR(20),

    -- Datos del vehículo
    CO_VEHICULO_MARCA NVARCHAR(100),
    CO_VEHICULO_MODELO NVARCHAR(100),

    -- Obsequios
    CO_OBSEQUIOS NTEXT,

    FOREIGN KEY (CO_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_CARTA_CARACTERISTICAS_BANBIF
-- =====================================================

CREATE TABLE SIST_CARTA_CARACTERISTICAS_BANBIF (
    CCB_ID INT IDENTITY(1,1) PRIMARY KEY,
    CCB_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CCB_DOCUMENTO_VENTA_ID INT,

    -- Encabezado
    CCB_FECHA_CARTA NVARCHAR(100),
    CCB_EMPRESA_DESTINO NVARCHAR(200),

    -- Datos del cliente
    CCB_CLIENTE_NOMBRE NVARCHAR(200),
    CCB_CLIENTE_DNI NVARCHAR(20),

    -- Datos del vehículo
    CCB_VEHICULO_MARCA NVARCHAR(100),
    CCB_VEHICULO_MODELO NVARCHAR(100),
    CCB_VEHICULO_ANIO_MODELO NVARCHAR(10),
    CCB_VEHICULO_CHASIS NVARCHAR(50),
    CCB_VEHICULO_MOTOR NVARCHAR(50),
    CCB_VEHICULO_CARROCERIA NVARCHAR(50),
    CCB_VEHICULO_COLOR NVARCHAR(50),

    -- Valores
    CCB_PRECIO_VEHICULO DECIMAL(12,2),
    CCB_MONTO_DESEMBOLSO DECIMAL(12,2),
    CCB_PROPIETARIO_TARJETA NVARCHAR(200),

    FOREIGN KEY (CCB_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_POLITICA_PROTECCION_DATOS
-- =====================================================

CREATE TABLE SIST_POLITICA_PROTECCION_DATOS (
    PPD_ID INT IDENTITY(1,1) PRIMARY KEY,
    PPD_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    PPD_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    PPD_CLIENTE_NOMBRE NVARCHAR(200),
    PPD_CLIENTE_DNI NVARCHAR(20),
    PPD_FECHA_AUTORIZACION DATE,

    FOREIGN KEY (PPD_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- VERIFICACIÓN Y ACTUALIZACIÓN AUTOMÁTICA
-- Agrega campos faltantes si la tabla ya existe
-- =====================================================

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'SIST_ORDEN_COMPRA')
BEGIN
    PRINT '📋 Tabla existente encontrada. Verificando campos faltantes...';

    -- Campos duplicados (fechas y teléfonos)
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_FECHA_NACIMIENTO_NUEVO')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_FECHA_NACIMIENTO_NUEVO DATE;
        PRINT '✅ Campo OC_FECHA_NACIMIENTO_NUEVO (segunda fecha) agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_TELEFONO_ADICIONAL')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_TELEFONO_ADICIONAL NVARCHAR(100);
        PRINT '✅ Campo OC_TELEFONO_ADICIONAL agregado.';
    END

    -- Campos de firmas y huellas
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ASESOR_NOMBRE')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ASESOR_NOMBRE NVARCHAR(200);
        PRINT '✅ Campo OC_ASESOR_NOMBRE agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ASESOR_FIRMA')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ASESOR_FIRMA NVARCHAR(200);
        PRINT '✅ Campo OC_ASESOR_FIRMA agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ASESOR_HUELLA')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ASESOR_HUELLA NVARCHAR(200);
        PRINT '✅ Campo OC_ASESOR_HUELLA agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_CLIENTE_FIRMA')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_CLIENTE_FIRMA NVARCHAR(200);
        PRINT '✅ Campo OC_CLIENTE_FIRMA agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_CLIENTE_HUELLA')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_CLIENTE_HUELLA NVARCHAR(200);
        PRINT '✅ Campo OC_CLIENTE_HUELLA agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_JEFE_NOMBRE')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_JEFE_NOMBRE NVARCHAR(200);
        PRINT '✅ Campo OC_JEFE_NOMBRE agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_JEFE_FIRMA')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_JEFE_FIRMA NVARCHAR(200);
        PRINT '✅ Campo OC_JEFE_FIRMA agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_JEFE_HUELLA')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_JEFE_HUELLA NVARCHAR(200);
        PRINT '✅ Campo OC_JEFE_HUELLA agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_VISTO_ADV')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_VISTO_ADV NVARCHAR(200);
        PRINT '✅ Campo OC_VISTO_ADV agregado.';
    END

    -- Campos de archivos adjuntos
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_DNI')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_DNI NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_DNI agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_VOUCHER')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_VOUCHER NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_VOUCHER agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_PEDIDO_SALESFORCE')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_PEDIDO_SALESFORCE NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_PEDIDO_SALESFORCE agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_DERIVACION_SANTANDER')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_DERIVACION_SANTANDER NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_DERIVACION_SANTANDER agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVOS_ABONOS')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVOS_ABONOS NVARCHAR(MAX);
        PRINT '✅ Campo OC_ARCHIVOS_ABONOS agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_ABONO_1')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_ABONO_1 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_ABONO_1 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_ABONO_2')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_ABONO_2 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_ABONO_2 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_ABONO_3')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_ABONO_3 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_ABONO_3 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_ABONO_4')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_ABONO_4 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_ABONO_4 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_ABONO_5')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_ABONO_5 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_ABONO_5 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_ABONO_6')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_ABONO_6 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_ABONO_6 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_OTROS_1')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_OTROS_1 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_OTROS_1 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_OTROS_2')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_OTROS_2 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_OTROS_2 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_OTROS_3')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_OTROS_3 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_OTROS_3 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_OTROS_4')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_OTROS_4 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_OTROS_4 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_OTROS_5')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_OTROS_5 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_OTROS_5 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_ARCHIVO_OTROS_6')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_ARCHIVO_OTROS_6 NVARCHAR(500);
        PRINT '✅ Campo OC_ARCHIVO_OTROS_6 agregado.';
    END

    -- Campos de descripción de equipamiento adicional
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_DESCRIPCION_EQUIPAMIENTO_1')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_DESCRIPCION_EQUIPAMIENTO_1 NVARCHAR(200);
        PRINT '✅ Campo OC_DESCRIPCION_EQUIPAMIENTO_1 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_DESCRIPCION_EQUIPAMIENTO_2')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_DESCRIPCION_EQUIPAMIENTO_2 NVARCHAR(200);
        PRINT '✅ Campo OC_DESCRIPCION_EQUIPAMIENTO_2 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_DESCRIPCION_EQUIPAMIENTO_3')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_DESCRIPCION_EQUIPAMIENTO_3 NVARCHAR(200);
        PRINT '✅ Campo OC_DESCRIPCION_EQUIPAMIENTO_3 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_DESCRIPCION_EQUIPAMIENTO_4')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_DESCRIPCION_EQUIPAMIENTO_4 NVARCHAR(200);
        PRINT '✅ Campo OC_DESCRIPCION_EQUIPAMIENTO_4 agregado.';
    END

    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_DESCRIPCION_EQUIPAMIENTO_5')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA ADD OC_DESCRIPCION_EQUIPAMIENTO_5 NVARCHAR(200);
        PRINT '✅ Campo OC_DESCRIPCION_EQUIPAMIENTO_5 agregado.';
    END

    -- Verificar y actualizar tipo de dato de OC_TIPO_CAMBIO_SOL
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_TIPO_CAMBIO_SOL')
    BEGIN
        DECLARE @current_precision INT;
        SELECT @current_precision = precision FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_TIPO_CAMBIO_SOL';
        IF @current_precision < 12
        BEGIN
            ALTER TABLE SIST_ORDEN_COMPRA ALTER COLUMN OC_TIPO_CAMBIO_SOL DECIMAL(12,2);
            PRINT '✅ Tipo de dato de OC_TIPO_CAMBIO_SOL actualizado a DECIMAL(12,2).';
        END
    END

    -- Eliminar campo OC_USO_VEHICULO si existe (ya no se usa)
    IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('SIST_ORDEN_COMPRA') AND name = 'OC_USO_VEHICULO')
    BEGIN
        ALTER TABLE SIST_ORDEN_COMPRA DROP COLUMN OC_USO_VEHICULO;
        PRINT '✅ Campo OC_USO_VEHICULO eliminado (ya no se usa).';
    END

    PRINT '🔄 Verificación automática completada.';
END
ELSE
BEGIN
    PRINT '🆕 Nueva tabla creada con todos los campos incluidos.';
END

PRINT '✅ BASE DE DATOS FACCARPRUEBA COMPLETA'
PRINT '📋 Campos incluidos:'
PRINT '👥 Cliente: 2 fechas nacimiento 2 teléfonos'
PRINT '✍️ Firmas: asesor cliente jefe de tienda'
PRINT '🔍 Huellas: asesor cliente jefe de tienda'
PRINT '📝 Visto ADV: campo temporal'
PRINT '🚀 Total: 70+ campos organizados por orden del formulario'