-- =====================================================
-- BASE DE DATOS: documentos_db
-- Esquema adaptado para MySQL con patrón SIST_ para tablas y campos
-- Versión completa con campos duplicados y firmas
-- =====================================================

-- Crear base de datos
CREATE DATABASE IF NOT EXISTS documentos_db;
USE documentos_db;

-- =====================================================
-- TABLA PRINCIPAL: SIST_ORDEN_COMPRA
-- Contiene todos los campos de la orden de compra
-- =====================================================

CREATE TABLE SIST_ORDEN_COMPRA (
    OC_ID INT AUTO_INCREMENT PRIMARY KEY,
    OC_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- ENCABEZADO (orden del formulario)
    OC_NUMERO_EXPEDIENTE VARCHAR(50),
    OC_NUMERO_COTIZACION VARCHAR(50),
    OC_FECHA_ORDEN DATE,
    OC_ASESOR_VENTA VARCHAR(100),

    -- DATOS DEL CLIENTE - COMPRADOR (orden del formulario)
    OC_COMPRADOR_NOMBRE VARCHAR(200),
    OC_COMPRADOR_TIPO_DOCUMENTO VARCHAR(20), -- DNI, PASAPORTE, CARNET EXTRANJERIA, RUC
    OC_COMPRADOR_NUMERO_DOCUMENTO VARCHAR(20),
    OC_TIPO_DOCUMENTO_VENTA VARCHAR(20), -- BOLETA DE VENTA, FACTURA DE VENTA
    OC_FUENTE_CONTACTO VARCHAR(100), -- Digital Marca, Digital Dealer, etc.

    -- INFORMACIÓN PERSONAL DEL CLIENTE (orden del formulario)
    OC_FECHA_NACIMIENTO DATE, -- Primera fecha de nacimiento (junto a estado civil)
    OC_ESTADO_CIVIL VARCHAR(20), -- SOLTERO, CASADO, DIVORCIADO, SEPARADO, CONCUBINA(O), CONVIVIENTE
    OC_SITUACION_LABORAL VARCHAR(50), -- EMPLEADO, INDEPENDIENTE, NEGOCIANTE, JUBILADO, DEPENDIENTE, DESEMPLEADO, OTROS

    -- DATOS DEL CÓNYUGE (orden del formulario)
    OC_CONYUGE_NOMBRE VARCHAR(200),
    OC_CONYUGE_TIPO_DOCUMENTO VARCHAR(20),
    OC_CONYUGE_NUMERO_DOCUMENTO VARCHAR(20),

    -- INFORMACIÓN DE CONTACTO (orden del formulario)
    OC_DIRECCION_CLIENTE VARCHAR(300),
    OC_TELEFONOS_CLIENTE VARCHAR(100), -- Teléfono principal
    OC_EMAIL_CLIENTE VARCHAR(150),
    OC_TELEFONO_ADICIONAL VARCHAR(100), -- Teléfono adicional
    OC_OCUPACION_CLIENTE VARCHAR(100),
    OC_HOBBIES_CLIENTE VARCHAR(200),
    OC_FECHA_NACIMIENTO_NUEVO DATE, -- Segunda fecha de nacimiento (junto a hobbies)

    -- TARJETA DE PROPIEDAD (orden del formulario)
    OC_TARJETA_PROPIEDAD VARCHAR(50), -- natural, ruc, juridica

    -- PROPIETARIOS (orden del formulario)
    OC_PROPIETARIO_NOMBRE VARCHAR(200),
    OC_PROPIETARIO_DNI VARCHAR(20),
    OC_COPROPIETARIO_NOMBRE VARCHAR(200),
    OC_COPROPIETARIO_DNI VARCHAR(20),
    OC_REPRESENTANTE_LEGAL VARCHAR(200),
    OC_REPRESENTANTE_DNI VARCHAR(20),

    -- DATOS DEL VEHÍCULO (orden del formulario)
    OC_VEHICULO_CLASE VARCHAR(100),
    OC_VEHICULO_MARCA VARCHAR(100),
    OC_VEHICULO_MODELO VARCHAR(100),
    OC_VEHICULO_VERSION VARCHAR(100),
    OC_VEHICULO_CODIGO_FSC VARCHAR(100),
    OC_VEHICULO_MOTOR VARCHAR(100),
    OC_VEHICULO_CHASIS VARCHAR(100),
    OC_VEHICULO_COLOR VARCHAR(50),
    OC_VEHICULO_ANIO_MODELO VARCHAR(10),
    OC_PERIODO_GARANTIA VARCHAR(100),
    OC_PERIODICIDAD_MANTENIMIENTO VARCHAR(100),
    OC_PRIMER_MANTENIMIENTO VARCHAR(100),
    OC_USO_VEHICULO VARCHAR(20), -- particular, servicio

    -- VALOR DE LA COMPRA / FORMA DE PAGO (orden del formulario)
    OC_FORMA_PAGO VARCHAR(20), -- CONTADO, CRÉDITO
    OC_PRECIO_VENTA DECIMAL(12,2),
    OC_MONEDA_PRECIO_VENTA VARCHAR(5), -- US$, MN
    OC_BONO_FINANCIAMIENTO DECIMAL(12,2),
    OC_MONEDA_BONO_FINANCIAMIENTO VARCHAR(5),

    -- EQUIPAMIENTO ADICIONAL (orden del formulario)
    OC_EQUIPAMIENTO_ADICIONAL_1 VARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_1 VARCHAR(5),
    OC_EQUIPAMIENTO_ADICIONAL_2 VARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_2 VARCHAR(5),
    OC_EQUIPAMIENTO_ADICIONAL_3 VARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_3 VARCHAR(5),
    OC_EQUIPAMIENTO_ADICIONAL_4 VARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_4 VARCHAR(5),
    OC_EQUIPAMIENTO_ADICIONAL_5 VARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_5 VARCHAR(5),

    OC_TOTAL_EQUIPAMIENTO DECIMAL(12,2),
    OC_PRECIO_TOTAL_COMPRA DECIMAL(12,2),
    OC_MONEDA_PRECIO_TOTAL VARCHAR(5),
    OC_TIPO_CAMBIO DECIMAL(8,4),
    OC_TIPO_CAMBIO_SOL DECIMAL(8,4),

    -- FORMA DE PAGO - COLUMNA DERECHA (orden del formulario)
    OC_PAGO_CUENTA DECIMAL(12,2),
    OC_MONEDA_PAGO_CUENTA VARCHAR(5),
    OC_NUMERO_OPERACION VARCHAR(50),
    OC_NUMERO_OPERACION_2 VARCHAR(50),
    OC_ENTIDAD_FINANCIERA VARCHAR(100),
    OC_SALDO_PENDIENTE DECIMAL(12,2),
    OC_MONEDA_SALDO VARCHAR(5),

    -- INFORMACIÓN BANCARIA (orden del formulario)
    OC_BANCO_ABONO VARCHAR(100),
    OC_SECTORISTA_BANCO VARCHAR(100),
    OC_OFICINA_BANCO VARCHAR(100),
    OC_TELEFONO_SECTORISTA VARCHAR(20),

    -- OBSEQUIOS Y CAMPAÑAS (orden del formulario)
    OC_OBSEQUIOS_CORTESIAS TEXT,

    -- FIRMAS Y HUELLAS (orden del formulario)
    OC_ASESOR_NOMBRE VARCHAR(200), -- Nombre del asesor de venta
    OC_ASESOR_FIRMA VARCHAR(200), -- Firma del asesor
    OC_ASESOR_HUELLA VARCHAR(200), -- Huella del asesor
    OC_CLIENTE_FIRMA VARCHAR(200), -- Firma del cliente
    OC_CLIENTE_HUELLA VARCHAR(200), -- Huella del cliente
    OC_JEFE_NOMBRE VARCHAR(200), -- Nombre del jefe de tienda
    OC_JEFE_FIRMA VARCHAR(200), -- Firma del jefe
    OC_JEFE_HUELLA VARCHAR(200), -- Huella del jefe
    OC_VISTO_ADV VARCHAR(200) -- Visto ADV (por definir)
);

-- =====================================================
-- TABLA: SIST_ACTA_CONOCIMIENTO_CONFORMIDAD
-- =====================================================

CREATE TABLE SIST_ACTA_CONOCIMIENTO_CONFORMIDAD (
    ACC_ID INT AUTO_INCREMENT PRIMARY KEY,
    ACC_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACC_DOCUMENTO_VENTA_ID INT,

    -- Datos del acta
    ACC_FECHA_ACTA DATE,
    ACC_NOMBRE_CLIENTE VARCHAR(200),
    ACC_DNI_CLIENTE VARCHAR(20),
    ACC_EMPRESA_INSTALADORA VARCHAR(200),

    -- Datos del vehículo
    ACC_BOLETA_FACTURA_NUMERO VARCHAR(50),
    ACC_CLIENTE_VEHICULO VARCHAR(200),
    ACC_FECHA_VENTA DATE,
    ACC_MARCA_VEHICULO VARCHAR(100),
    ACC_MODELO_VEHICULO VARCHAR(100),
    ACC_ANIO_VEHICULO VARCHAR(10),
    ACC_VIN_VEHICULO VARCHAR(50),
    ACC_COLOR_VEHICULO VARCHAR(50),

    -- Firmas
    ACC_FIRMA_CLIENTE VARCHAR(200),
    ACC_NOMBRE_FIRMA VARCHAR(200),
    ACC_DNI_FIRMA VARCHAR(20),

    FOREIGN KEY (ACC_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_AUTORIZACION_DATOS_PERSONALES
-- =====================================================

CREATE TABLE SIST_AUTORIZACION_DATOS_PERSONALES (
    ADP_ID INT AUTO_INCREMENT PRIMARY KEY,
    ADP_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADP_DOCUMENTO_VENTA_ID INT,

    -- Datos de autorización
    ADP_NOMBRE_AUTORIZACION VARCHAR(200),
    ADP_DNI_AUTORIZACION VARCHAR(20),
    ADP_FECHA_AUTORIZACION DATE,

    FOREIGN KEY (ADP_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_CARTA_CONOCIMIENTO_ACEPTACION
-- =====================================================

CREATE TABLE SIST_CARTA_CONOCIMIENTO_ACEPTACION (
    CCA_ID INT AUTO_INCREMENT PRIMARY KEY,
    CCA_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CCA_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    CCA_CLIENTE_NOMBRE_COMPLETO VARCHAR(200),
    CCA_CLIENTE_DOCUMENTO VARCHAR(50),

    -- Datos del vehículo
    CCA_VEHICULO_MARCA VARCHAR(100),
    CCA_VEHICULO_MODELO VARCHAR(100),
    CCA_VEHICULO_ANIO VARCHAR(10),
    CCA_VEHICULO_VIN VARCHAR(50),

    -- Firmas
    CCA_FIRMA_CLIENTE VARCHAR(200),
    CCA_NOMBRE_FIRMA VARCHAR(200),
    CCA_DOCUMENTO_FIRMA VARCHAR(50),
    CCA_FECHA_FIRMA DATE,

    FOREIGN KEY (CCA_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_CARTA_RECEPCION
-- =====================================================

CREATE TABLE SIST_CARTA_RECEPCION (
    CR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CR_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CR_DOCUMENTO_VENTA_ID INT,

    -- Fechas
    CR_FECHA_DIA VARCHAR(2),
    CR_FECHA_MES VARCHAR(20),
    CR_FECHA_ANIO VARCHAR(4),

    -- Datos del cliente
    CR_CLIENTE_NOMBRE VARCHAR(200),
    CR_CLIENTE_DNI VARCHAR(20),

    -- Datos del vehículo
    CR_VEHICULO_MARCA VARCHAR(100),
    CR_VEHICULO_MODELO VARCHAR(100),

    FOREIGN KEY (CR_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_CARTA_CARACTERISTICAS
-- =====================================================

CREATE TABLE SIST_CARTA_CARACTERISTICAS (
    CC_ID INT AUTO_INCREMENT PRIMARY KEY,
    CC_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CC_DOCUMENTO_VENTA_ID INT,

    -- Encabezado
    CC_FECHA_CARTA VARCHAR(100),
    CC_EMPRESA_DESTINO VARCHAR(200),

    -- Datos del cliente
    CC_CLIENTE_NOMBRE VARCHAR(200),
    CC_CLIENTE_DNI VARCHAR(20),

    -- Datos del vehículo
    CC_VEHICULO_MARCA VARCHAR(100),
    CC_VEHICULO_MODELO VARCHAR(100),
    CC_VEHICULO_ANIO_MODELO VARCHAR(10),
    CC_VEHICULO_CHASIS VARCHAR(50),
    CC_VEHICULO_MOTOR VARCHAR(50),
    CC_VEHICULO_CARROCERIA VARCHAR(50),
    CC_VEHICULO_COLOR VARCHAR(50),

    -- Valores
    CC_PRECIO_VEHICULO DECIMAL(12,2),
    CC_MONTO_DESEMBOLSO DECIMAL(12,2),
    CC_PROPIETARIO_TARJETA VARCHAR(200),

    FOREIGN KEY (CC_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_CARTA_FELICITACIONES
-- =====================================================

CREATE TABLE SIST_CARTA_FELICITACIONES (
    CF_ID INT AUTO_INCREMENT PRIMARY KEY,
    CF_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CF_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    CF_CLIENTE_NOMBRE VARCHAR(200),
    CF_VEHICULO_MARCA VARCHAR(100),

    -- Datos del asesor
    CF_ASESOR_NOMBRE VARCHAR(200),
    CF_ASESOR_CELULAR VARCHAR(20),

    -- Aplicación
    CF_APLICACION_NOMBRE VARCHAR(200),

    FOREIGN KEY (CF_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_CARTA_OBSEQUIOS
-- =====================================================

CREATE TABLE SIST_CARTA_OBSEQUIOS (
    CO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CO_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    CO_CLIENTE_NOMBRE VARCHAR(200),
    CO_CLIENTE_DNI VARCHAR(20),

    -- Datos del vehículo
    CO_VEHICULO_MARCA VARCHAR(100),
    CO_VEHICULO_MODELO VARCHAR(100),

    -- Obsequios
    CO_OBSEQUIOS TEXT,

    FOREIGN KEY (CO_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_POLITICA_PROTECCION_DATOS
-- =====================================================

CREATE TABLE SIST_POLITICA_PROTECCION_DATOS (
    PPD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PPD_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PPD_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    PPD_CLIENTE_NOMBRE VARCHAR(200),
    PPD_CLIENTE_DNI VARCHAR(20),
    PPD_FECHA_AUTORIZACION DATE,

    FOREIGN KEY (PPD_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- ÍNDICES PARA MEJOR PERFORMANCE
-- =====================================================

CREATE INDEX IDX_OC_FECHA_ORDEN ON SIST_ORDEN_COMPRA(OC_FECHA_ORDEN);
CREATE INDEX IDX_OC_CLIENTE_NOMBRE ON SIST_ORDEN_COMPRA(OC_COMPRADOR_NOMBRE);
CREATE INDEX IDX_OC_ASESOR_VENTA ON SIST_ORDEN_COMPRA(OC_ASESOR_VENTA);

CREATE INDEX IDX_ACC_FECHA_ACTA ON SIST_ACTA_CONOCIMIENTO_CONFORMIDAD(ACC_FECHA_ACTA);
CREATE INDEX IDX_ADP_FECHA_AUTORIZACION ON SIST_AUTORIZACION_DATOS_PERSONALES(ADP_FECHA_AUTORIZACION);
CREATE INDEX IDX_CCA_FECHA_FIRMA ON SIST_CARTA_CONOCIMIENTO_ACEPTACION(CCA_FECHA_FIRMA);