-- =====================================================
-- BASE DE DATOS: FACCARPRUEBA
-- Esquema con patrón SIST_ para tablas y campos
-- Versión completa con campos duplicados y firmas
-- =====================================================

PRINT '🚀 Iniciando creación/actualización de base de datos FACCARPRUEBA...'
PRINT '📋 Incluye campos duplicados (2 fechas nacimiento 2 teléfonos) y campos de firmas'

-- =====================================================
-- TABLA PRINCIPAL: SIST_ORDEN_COMPRA
-- Contiene todos los campos de la orden de compra
-- =====================================================

CREATE TABLE SIST_ORDEN_COMPRA (
    OC_ID INT IDENTITY(1,1) PRIMARY KEY,
    OC_FECHA_CREACION DATETIME DEFAULT GETDATE(),

    -- ENCABEZADO (orden del formulario)
    OC_NUMERO_EXPEDIENTE NVARCHAR(50),
    OC_NUMERO_COTIZACION NVARCHAR(50),
    
    -- CENTRO DE COSTO Y APROBACIÓN (orden del formulario)
    OC_AGENCIA NVARCHAR(100),
    OC_NOMBRE_RESPONSABLE NVARCHAR(200),
    OC_CENTRO_COSTO NVARCHAR(50),
    OC_EMAIL_CENTRO_COSTO NVARCHAR(150),
    
    OC_FECHA_ORDEN DATE,
    OC_ASESOR_VENTA NVARCHAR(100),

    -- DATOS DEL CLIENTE - COMPRADOR (orden del formulario)
    OC_TIPO_CLIENTE NVARCHAR(50), -- Tipo de cliente: natural, ruc, juridica
    OC_COMPRADOR_NOMBRE NVARCHAR(200),
    OC_COMPRADOR_APELLIDO NVARCHAR(200),
    OC_COMPRADOR_TIPO_DOCUMENTO NVARCHAR(20), -- DNI, PASAPORTE, CARNET EXTRANJERIA, RUC
    OC_COMPRADOR_NUMERO_DOCUMENTO NVARCHAR(20),
    OC_TIPO_DOCUMENTO_VENTA NVARCHAR(20), -- BOLETA DE VENTA, FACTURA DE VENTA
    OC_FUENTE_CONTACTO NVARCHAR(100), -- Digital Marca, Digital Dealer, etc.
    

    -- INFORMACIÓN PERSONAL DEL CLIENTE (orden del formulario)
    OC_FECHA_NACIMIENTO DATE, -- Primera fecha de nacimiento (junto a estado civil)
    OC_ESTADO_CIVIL NVARCHAR(20), -- SOLTERO, CASADO, DIVORCIADO, SEPARADO, CONCUBINA(O), CONVIVIENTE
    OC_SITUACION_LABORAL NVARCHAR(50), -- EMPLEADO, INDEPENDIENTE, NEGOCIANTE, JUBILADO, DEPENDIENTE, DESEMPLEADO, OTROS

    -- DATOS DEL CÓNYUGE (orden del formulario)
    OC_CONYUGE_NOMBRE NVARCHAR(200),
    OC_CONYUGE_TIPO_DOCUMENTO NVARCHAR(20),
    OC_CONYUGE_NUMERO_DOCUMENTO NVARCHAR(20),

    -- INFORMACIÓN DE CONTACTO (orden del formulario)
    OC_DIRECCION_CLIENTE NVARCHAR(300),
    OC_TELEFONO_CLIENTE NVARCHAR(100), -- Teléfono principal
    OC_EMAIL_CLIENTE NVARCHAR(150),
    OC_EMAIL_CLIENTE_2 NVARCHAR(150), -- Email secundario del cliente
    OC_TELEFONO_ADICIONAL NVARCHAR(100), -- Teléfono adicional
    OC_OCUPACION_CLIENTE NVARCHAR(100),
    OC_HOBBIES_CLIENTE NVARCHAR(200),
    

    -- TARJETA DE PROPIEDAD (orden del formulario)
    -- PROPIETARIOS (orden del formulario)
    OC_PROPIETARIO_NOMBRE NVARCHAR(200),
    OC_PROPIETARIO_DNI NVARCHAR(20),
    OC_COPROPIETARIO_NOMBRE NVARCHAR(200),
    OC_COPROPIETARIO_DNI NVARCHAR(20),
    OC_REPRESENTANTE_LEGAL NVARCHAR(200),
    OC_REPRESENTANTE_DNI NVARCHAR(20),
    OC_TARJETA_NOMBRE NVARCHAR(200), -- Tarjeta a nombre de (auto-rellena con nombre comprador)

    -- DATOS DEL VEHÍCULO (orden del formulario)
    OC_VEHICULO_CLASE NVARCHAR(100),
    OC_VEHICULO_MARCA NVARCHAR(100),
    OC_VEHICULO_MODELO NVARCHAR(100),
    OC_VEHICULO_VERSION NVARCHAR(100),
    OC_VEHICULO_CODIGO_FSC NVARCHAR(100),
    OC_VEHICULO_MOTOR NVARCHAR(100),
    OC_VEHICULO_CHASIS NVARCHAR(100),
    OC_VEHICULO_TIPO_COMBUSTIBLE NVARCHAR(10), -- Tipo de combustible (DU = GLP)
    OC_VEHICULO_COLOR NVARCHAR(50),
    OC_VEHICULO_ANIO_MODELO NVARCHAR(10),
    OC_PERIODO_GARANTIA NVARCHAR(100),
    OC_PERIODICIDAD_MANTENIMIENTO NVARCHAR(100),
    OC_PRIMER_MANTENIMIENTO NVARCHAR(100),

    -- VALOR DE LA COMPRA / FORMA DE PAGO (orden del formulario)
    OC_FORMA_PAGO NVARCHAR(20), -- CONTADO, CRÉDITO
    OC_PRECIO_VENTA DECIMAL(12,2),
    OC_MONEDA_PRECIO_VENTA NVARCHAR(5), -- US$, MN
    OC_BONO_FINANCIAMIENTO DECIMAL(12,2),
    OC_MONEDA_BONO_FINANCIAMIENTO NVARCHAR(5),
    OC_MONEDA_BONO_CAMPANA NVARCHAR(5),
    OC_BONO_CAMPANA DECIMAL(12,2),
    OC_MONEDA_CUOTA_INICIAL NVARCHAR(5),
    OC_CUOTA_INICIAL DECIMAL(12,2),
    OC_COMENTARIO_VALIDACION NVARCHAR(MAX), -- Comentario cuando no cumple validaciones de pago

    -- EQUIPAMIENTO ADICIONAL (orden del formulario)
    OC_DESCRIPCION_EQUIPAMIENTO_1 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_1 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_1 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_2 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_2 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_2 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_3 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_3 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_3 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_4 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_4 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_4 NVARCHAR(5),
    OC_DESCRIPCION_EQUIPAMIENTO_5 NVARCHAR(200),
    OC_EQUIPAMIENTO_ADICIONAL_5 NVARCHAR(200),
    OC_MONEDA_EQUIPAMIENTO_5 NVARCHAR(5),

    OC_TOTAL_EQUIPAMIENTO DECIMAL(12,2),
    OC_PRECIO_TOTAL_COMPRA DECIMAL(12,2),
    OC_MONEDA_PRECIO_TOTAL NVARCHAR(5),
    OC_TIPO_CAMBIO DECIMAL(8,4),
    OC_TIPO_CAMBIO_SOL DECIMAL(12,2),
    OC_FAKE_PRECIO BIT DEFAULT 0,

    -- FORMA DE PAGO - COLUMNA DERECHA (orden del formulario)
    OC_PAGO_CUENTA DECIMAL(12,2),
    OC_MONEDA_PAGO_CUENTA NVARCHAR(5),
    OC_SALDO_PENDIENTE DECIMAL(12,2),
    OC_MONEDA_SALDO NVARCHAR(5),
    OC_NUMERO_OPERACION NVARCHAR(50),
    OC_NUMERO_OPERACION_2 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA NVARCHAR(100),


     -- DETALLE DE ABONOS (hasta 7 abonos)
    OC_MONTO_1 NVARCHAR(50),
    OC_NRO_OPERACION_1 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA_1 NVARCHAR(100),
    OC_ARCHIVO_ABONO1 NVARCHAR(500),
    
    OC_MONTO_2 NVARCHAR(50),
    OC_NRO_OPERACION_2 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA_2 NVARCHAR(100),
    OC_ARCHIVO_ABONO2 NVARCHAR(500),
    
    OC_MONTO_3 NVARCHAR(50),
    OC_NRO_OPERACION_3 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA_3 NVARCHAR(100),
    OC_ARCHIVO_ABONO3 NVARCHAR(500),
    
    OC_MONTO_4 NVARCHAR(50),
    OC_NRO_OPERACION_4 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA_4 NVARCHAR(100),
    OC_ARCHIVO_ABONO4 NVARCHAR(500),
    
    OC_MONTO_5 NVARCHAR(50),
    OC_NRO_OPERACION_5 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA_5 NVARCHAR(100),
    OC_ARCHIVO_ABONO5 NVARCHAR(500),
    
    OC_MONTO_6 NVARCHAR(50),
    OC_NRO_OPERACION_6 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA_6 NVARCHAR(100),
    OC_ARCHIVO_ABONO6 NVARCHAR(500),
    
    OC_MONTO_7 NVARCHAR(50),
    OC_NRO_OPERACION_7 NVARCHAR(50),
    OC_ENTIDAD_FINANCIERA_7 NVARCHAR(100),
    OC_ARCHIVO_ABONO7 NVARCHAR(500),

    -- INFORMACIÓN BANCARIA (orden del formulario)
    OC_BANCO_ABONO NVARCHAR(100),
    OC_SECTORISTA_BANCO NVARCHAR(100),
    OC_OFICINA_BANCO NVARCHAR(100),
    OC_TELEFONO_SECTORISTA NVARCHAR(20),


     -- ARCHIVOS ADJUNTOS (orden del formulario)
    OC_ARCHIVO_DNI NVARCHAR(500),
    OC_ARCHIVO_PEDIDO_SALESFORCE NVARCHAR(500),
    OC_ARCHIVO_OTROS_1 NVARCHAR(500),
    OC_ARCHIVO_OTROS_2 NVARCHAR(500),
    OC_ARCHIVO_OTROS_3 NVARCHAR(500),
    OC_ARCHIVO_OTROS_4 NVARCHAR(500),
    OC_ARCHIVO_OTROS_5 NVARCHAR(500),
    OC_ARCHIVO_OTROS_6 NVARCHAR(500),


    -- OBSEQUIOS Y CAMPAÑAS (orden del formulario)
    OC_OBSEQUIOS_CORTESIAS NVARCHAR(MAX),

    -- FIRMAS Y HUELLAS (orden del formulario)
    OC_ASESOR_NOMBRE NVARCHAR(200), -- Nombre del asesor de venta
    OC_ASESOR_FIRMA NVARCHAR(200), -- Firma del asesor
    OC_ASESOR_HUELLA NVARCHAR(200), -- Huella del asesor
    OC_ASESOR_CELULAR NVARCHAR(50), -- Celular del asesor de venta
    OC_CLIENTE_FIRMA NVARCHAR(200), -- Firma del cliente
    OC_CONFIRMACION_SANTANDER NVARCHAR(200), -- Archivo de confirmación Santander (antes OC_CLIENTE_HUELLA)
    OC_JEFE_NOMBRE NVARCHAR(200), -- Nombre del jefe de tienda
    OC_JEFE_FIRMA NVARCHAR(200), -- Firma del jefe
    OC_JEFE_HUELLA NVARCHAR(200), -- Huella del jefe
    OC_VISTO_ADV NVARCHAR(200), -- Visto ADV (por definir)

  

    -- CAMPOS DE APROBACIÓN
    OC_ESTADO_APROBACION NVARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, APROBADO, RECHAZADO
    OC_FECHA_APROBACION DATETIME,
    OC_OBSERVACIONES_APROBACION NVARCHAR(500),
    
    -- CAMPOS DE USUARIO CREADOR (para notificaciones)
    OC_USUARIO_EMAIL NVARCHAR(255), -- Email del asesor que crea la orden
    OC_USUARIO_NOMBRE NVARCHAR(255),-- Nombre del asesor que crea la orden
    OC_ASESOR_MARCA NVARCHAR(100), 
    OC_TOKEN_APROBACION NVARCHAR(64)
);
;

-- =====================================================
-- TABLA: SIST_ACTA_CONOCIMIENTO_CONFORMIDAD
-- =====================================================

CREATE TABLE SIST_ACTA_CONOCIMIENTO_CONFORMIDAD (
    ACC_ID INT IDENTITY(1,1) PRIMARY KEY,
    ACC_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ACC_DOCUMENTO_VENTA_ID INT,

    -- Datos del acta
    ACC_FECHA_ACTA DATE,
    ACC_NOMBRE_CLIENTE NVARCHAR(200),
    ACC_DNI_CLIENTE NVARCHAR(20),
    ACC_EMPRESA_INSTALADORA NVARCHAR(200),

    -- Datos del vehículo
    ACC_BOLETA_FACTURA_NUMERO NVARCHAR(50),
    ACC_CLIENTE_VEHICULO NVARCHAR(200),
    ACC_FECHA_VENTA DATE,
    ACC_MARCA_VEHICULO NVARCHAR(100),
    ACC_MODELO_VEHICULO NVARCHAR(100),
    ACC_ANIO_VEHICULO NVARCHAR(10),
    ACC_VIN_VEHICULO NVARCHAR(50),
    ACC_COLOR_VEHICULO NVARCHAR(50),

    -- Firmas
    ACC_FIRMA_CLIENTE NVARCHAR(500),
    ACC_NOMBRE_FIRMA NVARCHAR(200),
    ACC_DNI_FIRMA NVARCHAR(20),

    FOREIGN KEY (ACC_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_AUTORIZACION_DATOS_PERSONALES
-- =====================================================

CREATE TABLE SIST_AUTORIZACION_DATOS_PERSONALES (
    ADP_ID INT IDENTITY(1,1) PRIMARY KEY,
    ADP_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ADP_DOCUMENTO_VENTA_ID INT,

    -- Datos de autorización
    ADP_NOMBRE_AUTORIZACION NVARCHAR(200),
    ADP_DNI_AUTORIZACION NVARCHAR(20),
    ADP_FECHA_AUTORIZACION DATE,

    -- Firma
    ADP_FIRMA_CLIENTE NVARCHAR(500),

    FOREIGN KEY (ADP_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_CARTA_CONOCIMIENTO_ACEPTACION
-- =====================================================

CREATE TABLE SIST_CARTA_CONOCIMIENTO_ACEPTACION (
    CCA_ID INT IDENTITY(1,1) PRIMARY KEY,
    CCA_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CCA_DOCUMENTO_VENTA_ID INT,

    -- Datos del cliente
    CCA_CLIENTE_NOMBRE_COMPLETO NVARCHAR(200),
    CCA_CLIENTE_DOCUMENTO NVARCHAR(50),

    -- Datos del vehículo
    CCA_VEHICULO_MARCA NVARCHAR(100),
    CCA_VEHICULO_MODELO NVARCHAR(100),
    CCA_VEHICULO_ANIO NVARCHAR(10),
    CCA_VEHICULO_VIN NVARCHAR(50),

    -- Firmas
    CCA_FIRMA_CLIENTE NVARCHAR(500),
    CCA_NOMBRE_FIRMA NVARCHAR(200),
    CCA_DOCUMENTO_FIRMA NVARCHAR(50),
    CCA_FECHA_FIRMA DATE,

    FOREIGN KEY (CCA_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_CARTA_RECEPCION
-- =====================================================

CREATE TABLE SIST_CARTA_RECEPCION (
    CR_ID INT IDENTITY(1,1) PRIMARY KEY,
    CR_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CR_DOCUMENTO_VENTA_ID INT,

    -- Fechas
    CR_FECHA_DIA NVARCHAR(10),
    CR_FECHA_MES NVARCHAR(50),
    CR_FECHA_ANIO NVARCHAR(10),

    -- Datos del cliente
    CR_CLIENTE_NOMBRE NVARCHAR(200),
    CR_CLIENTE_DNI NVARCHAR(20),

    -- Datos del vehículo
    CR_VEHICULO_MARCA NVARCHAR(100),
    CR_VEHICULO_MODELO NVARCHAR(100),

    -- Firma
    CR_FIRMA_CLIENTE NVARCHAR(500),

    FOREIGN KEY (CR_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_CARTA_CARACTERISTICAS
-- =====================================================

CREATE TABLE SIST_CARTA_CARACTERISTICAS (
    CC_ID INT IDENTITY(1,1) PRIMARY KEY,
    CC_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CC_DOCUMENTO_VENTA_ID INT,

    -- Encabezado
    CC_FECHA_CARTA NVARCHAR(100),
    CC_EMPRESA_DESTINO NVARCHAR(200),

    -- Datos del cliente
    CC_CLIENTE_NOMBRE NVARCHAR(200),
    CC_CLIENTE_DNI NVARCHAR(20),

    -- Datos del vehículo
    CC_VEHICULO_MARCA NVARCHAR(100),
    CC_VEHICULO_MODELO NVARCHAR(100),
    CC_VEHICULO_ANIO_MODELO NVARCHAR(10),
    CC_VEHICULO_CHASIS NVARCHAR(50),
    CC_VEHICULO_MOTOR NVARCHAR(50),
    CC_VEHICULO_CARROCERIA NVARCHAR(50),
    CC_VEHICULO_COLOR NVARCHAR(50),

    -- Valores
    CC_PRECIO_VEHICULO DECIMAL(12,2),
    CC_CUOTA_INICIAL DECIMAL(12,2),
    CC_MONTO_APROBADO_NETO DECIMAL(12,2),
    CC_CAMPANA_VEHICULO NVARCHAR(200),
    CC_PROPIETARIO_TARJETA NVARCHAR(200),

    FOREIGN KEY (CC_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_CARTA_CARACTERISTICAS_BANBIF
-- =====================================================

CREATE TABLE SIST_CARTA_CARACTERISTICAS_BANBIF (
    CCB_ID INT IDENTITY(1,1) PRIMARY KEY,
    CCB_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CCB_DOCUMENTO_VENTA_ID INT,

    -- Encabezado
    CCB_FECHA_CARTA DATE,
    CCB_NOMBRE_CONCESIONARIO NVARCHAR(200),
    CCB_RUC_CONCESIONARIO NVARCHAR(50),

    -- Datos del cliente
    CCB_CLIENTE_NOMBRE NVARCHAR(200),
    CCB_PROPIETARIO_TARJETA NVARCHAR(200),

    -- Datos del vehículo
    CCB_VEHICULO_MARCA NVARCHAR(100),
    CCB_VEHICULO_MODELO NVARCHAR(100),
    CCB_VEHICULO_ANIO_MODELO NVARCHAR(10),
    CCB_VEHICULO_COLOR NVARCHAR(50),
    CCB_VEHICULO_CLASE NVARCHAR(100),
    CCB_VEHICULO_MOTOR NVARCHAR(100),
    CCB_VEHICULO_CARROCERIA NVARCHAR(50),
    CCB_VEHICULO_CHASIS NVARCHAR(50),

    -- Información financiera
    CCB_PRECIO_VENTA_USD DECIMAL(12,2),
    CCB_PRECIO_VENTA_PEN DECIMAL(12,2),
    CCB_CUOTA_INICIAL_USD DECIMAL(12,2),
    CCB_CUOTA_INICIAL_PEN DECIMAL(12,2),
    CCB_SALDO_PRECIO_USD DECIMAL(12,2),
    CCB_SALDO_PRECIO_PEN DECIMAL(12,2),
    CCB_BENEFICIO_BANBIF_USD DECIMAL(12,2),
    CCB_BENEFICIO_BANBIF_PEN DECIMAL(12,2),

    -- Firma
    CCB_FIRMA_REPRESENTANTE NVARCHAR(500),

    FOREIGN KEY (CCB_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_CARTA_FELICITACIONES
-- =====================================================

CREATE TABLE SIST_CARTA_FELICITACIONES (
    CF_ID INT IDENTITY(1,1) PRIMARY KEY,
    CF_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    CF_DOCUMENTO_VENTA_ID INT,
    
    -- Datos del cliente
    CF_CLIENTE_NOMBRE NVARCHAR(200),
    
    -- Datos del vehículo
    CF_VEHICULO_MARCA NVARCHAR(100),
    CF_VEHICULO_MODELO NVARCHAR(100),
    CF_VEHICULO_VERSION NVARCHAR(100),
    
    -- Datos del asesor
    CF_ASESOR_NOMBRE NVARCHAR(200),
    CF_ASESOR_CELULAR NVARCHAR(50),
    
    -- Aplicación
    CF_APLICACION_NOMBRE NVARCHAR(200),
    
    FOREIGN KEY (CF_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);
;

-- =====================================================
-- TABLA: SIST_POLITICA_PROTECCION_DATOS
-- =====================================================

CREATE TABLE SIST_POLITICA_PROTECCION_DATOS (
    PPD_ID INT IDENTITY(1,1) PRIMARY KEY,
    PPD_FECHA_CREACION DATETIME DEFAULT GETDATE(),
    PPD_DOCUMENTO_VENTA_ID INT,
    PPD_CLIENTE_NOMBRE NVARCHAR(200),
    PPD_CLIENTE_DNI NVARCHAR(50),
    PPD_FECHA_AUTORIZACION DATE,
    PPD_FIRMA_CLIENTE NVARCHAR(500),
    FOREIGN KEY (PPD_DOCUMENTO_VENTA_ID) REFERENCES SIST_ORDEN_COMPRA(OC_ID)
);

-- =====================================================
-- TABLA: SIST_AUDIT_LOG
-- Sistema de auditoría para monitoreo de cambios
-- Registra todas las modificaciones realizadas por usuarios
-- =====================================================

CREATE TABLE SIST_AUDIT_LOG (
    AUDIT_ID INT IDENTITY(1,1) PRIMARY KEY,
    AUDIT_TIMESTAMP DATETIME DEFAULT GETDATE(),
    
    -- Información del usuario que realizó el cambio
    AUDIT_USER_ID NVARCHAR(100),           -- Usuario que hizo el cambio
    AUDIT_USER_NAME NVARCHAR(200),         -- Nombre completo del usuario
    AUDIT_USER_EMAIL NVARCHAR(255),        -- Email del usuario
    AUDIT_USER_ROLE NVARCHAR(50),          -- Rol del usuario (USER, ADMIN)
    
    -- Información del documento modificado
    AUDIT_DOCUMENT_TYPE NVARCHAR(100),     -- Tipo de documento (ORDEN_COMPRA, ACTA, etc.)
    AUDIT_DOCUMENT_ID INT,                 -- ID del documento modificado
    AUDIT_ORDEN_ID INT,                    -- ID de la orden de compra relacionada
    AUDIT_NUMERO_EXPEDIENTE NVARCHAR(50),  -- Número de expediente
    
    -- Detalles del cambio
    AUDIT_ACTION NVARCHAR(50),             -- Acción: INSERT, UPDATE, DELETE
    AUDIT_FIELD_NAME NVARCHAR(200),        -- Nombre del campo modificado
    AUDIT_OLD_VALUE NVARCHAR(MAX),         -- Valor anterior
    AUDIT_NEW_VALUE NVARCHAR(MAX),         -- Valor nuevo
    
    -- Información adicional
    AUDIT_IP_ADDRESS NVARCHAR(50),         -- Dirección IP del usuario
    AUDIT_SESSION_ID NVARCHAR(100),        -- ID de sesión
    AUDIT_DESCRIPTION NVARCHAR(500)        -- Descripción adicional del cambio
);

-- Índices para mejorar el rendimiento de consultas
CREATE INDEX IDX_AUDIT_TIMESTAMP ON SIST_AUDIT_LOG(AUDIT_TIMESTAMP DESC);
CREATE INDEX IDX_AUDIT_USER_ID ON SIST_AUDIT_LOG(AUDIT_USER_ID);
CREATE INDEX IDX_AUDIT_ORDEN_ID ON SIST_AUDIT_LOG(AUDIT_ORDEN_ID);
CREATE INDEX IDX_AUDIT_DOCUMENT_TYPE ON SIST_AUDIT_LOG(AUDIT_DOCUMENT_TYPE);
CREATE INDEX IDX_AUDIT_NUMERO_EXPEDIENTE ON SIST_AUDIT_LOG(AUDIT_NUMERO_EXPEDIENTE);

PRINT '✅ Tabla SIST_AUDIT_LOG creada exitosamente'
PRINT '📊 Sistema de auditoría listo para monitoreo de cambios'

-- =====================================================
-- TABLA: SIST_CONFIRMACIONES_CLIENTE
-- Registra las confirmaciones de los clientes sobre los documentos
-- que están firmando antes de enviar a cajera
-- =====================================================

CREATE TABLE SIST_CONFIRMACIONES_CLIENTE (
    CONF_ID INT IDENTITY(1,1) PRIMARY KEY,
    CONF_NUMERO_EXPEDIENTE NVARCHAR(50) NOT NULL,
    CONF_EMAIL_CLIENTE NVARCHAR(255) NOT NULL,
    CONF_TOKEN_CONFIRMACION NVARCHAR(100) NOT NULL UNIQUE,
    CONF_ESTADO NVARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, ACEPTADO, RECHAZADO
    CONF_FECHA_ENVIO DATETIME NOT NULL,
    CONF_FECHA_RESPUESTA DATETIME NULL,
    CONF_IP_CLIENTE NVARCHAR(45) NULL,
    CONF_OBSERVACIONES NVARCHAR(MAX) NULL,
    CONF_ENVIADO_CAJERA BIT DEFAULT 0,
    CONF_FECHA_ENVIO_CAJERA DATETIME NULL,
    CONF_CREATED_AT DATETIME DEFAULT GETDATE(),
    CONF_UPDATED_AT DATETIME DEFAULT GETDATE()
);

-- Índices para mejorar el rendimiento
CREATE INDEX IDX_CONF_EXPEDIENTE ON SIST_CONFIRMACIONES_CLIENTE(CONF_NUMERO_EXPEDIENTE);
CREATE INDEX IDX_CONF_TOKEN ON SIST_CONFIRMACIONES_CLIENTE(CONF_TOKEN_CONFIRMACION);
CREATE INDEX IDX_CONF_ESTADO ON SIST_CONFIRMACIONES_CLIENTE(CONF_ESTADO);
CREATE INDEX IDX_CONF_EMAIL ON SIST_CONFIRMACIONES_CLIENTE(CONF_EMAIL_CLIENTE);

PRINT '✅ Tabla SIST_CONFIRMACIONES_CLIENTE creada exitosamente'
PRINT '📧 Sistema de confirmación de cliente listo'

-- =====================================================
-- TABLA: SIST_CONFIRMACIONES_CAJERA
-- Registra las confirmaciones de la cajera sobre los documentos
-- que revisa después de la aprobación del cliente
-- =====================================================

CREATE TABLE SIST_CONFIRMACIONES_CAJERA (
    CAJERA_ID INT IDENTITY(1,1) PRIMARY KEY,
    CAJERA_NUMERO_EXPEDIENTE NVARCHAR(50) NOT NULL,
    CAJERA_EMAIL NVARCHAR(255) NOT NULL,
    CAJERA_TOKEN NVARCHAR(64) NOT NULL UNIQUE,
    CAJERA_ESTADO NVARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, APROBADO, RECHAZADO
    CAJERA_FECHA_ENVIO DATETIME DEFAULT GETDATE(),
    CAJERA_FECHA_RESPUESTA DATETIME,
    CAJERA_IP NVARCHAR(50),
    CAJERA_OBSERVACIONES NVARCHAR(MAX),
    CAJERA_FIRMA NVARCHAR(500) -- URL de la firma de la cajera (ejemplo: http://190.238.78.104:3800/robot-sdg-ford/firmas/cajera.png)
);

-- Índices para mejorar el rendimiento
CREATE INDEX IDX_CAJERA_EXPEDIENTE ON SIST_CONFIRMACIONES_CAJERA(CAJERA_NUMERO_EXPEDIENTE);
CREATE INDEX IDX_CAJERA_TOKEN ON SIST_CONFIRMACIONES_CAJERA(CAJERA_TOKEN);
CREATE INDEX IDX_CAJERA_ESTADO ON SIST_CONFIRMACIONES_CAJERA(CAJERA_ESTADO);
CREATE INDEX IDX_CAJERA_EMAIL ON SIST_CONFIRMACIONES_CAJERA(CAJERA_EMAIL);

PRINT '✅ Tabla SIST_CONFIRMACIONES_CAJERA creada exitosamente'
PRINT '📧 Sistema de confirmación de cajera listo'

